name: DockerHub-auto
on: push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Image
        run: docker build -t myimg .

      - name: Rename Img
        run: docker tag myimg eysha-raazia/mlops-tasks/myimg

      - name: Build and Push Docker Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64,linux/arm64 -t $DOCKER_USERNAME/myimg:latest .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push $DOCKER_USERNAME/myimg:latest
      
